import { SlidersHorizontal, RotateCcw } from 'lucide-react';
import { useFilters } from '../hooks/useFilters';
import { useDirectory } from '../hooks/queries';
import { priorities, channels, label } from '../services/format';
import { Button, ErrorBox } from './ui';
export function GlobalFilters() {
  const { filters, period, update, reset, error } = useFilters(); const directory = useDirectory();
  const teams = [...new Map((directory.data || []).map(x => [x.equipe.id, x.equipe])).values()];
  const techs = (directory.data || []).filter(t => !filters.equipeId || t.equipe.id === filters.equipeId);
  return <div className="filters-wrap"><div className="filter-bar"><span className="filter-icon"><SlidersHorizontal size={17}/></span><label>De<input aria-label="Período inicial" type="date" value={period.de} max={period.ate || undefined} onChange={e => update({ de: e.target.value })}/></label><label>Até<input aria-label="Período final" type="date" value={period.ate} min={period.de || undefined} onChange={e => update({ ate: e.target.value })}/></label><label>Equipe<select aria-label="Filtrar equipe" value={filters.equipeId || ''} onChange={e => update({ equipeId: e.target.value, tecnicoId: '' })}><option value="">Todas as equipes</option>{teams.map(t => <option key={t.id} value={t.id}>{t.nome}</option>)}</select></label><label>Técnico<select aria-label="Filtrar técnico" value={filters.tecnicoId || ''} onChange={e => update({ tecnicoId: e.target.value })}><option value="">Todos os técnicos</option>{techs.map(t => <option key={t.tecnico.id} value={t.tecnico.id}>{t.tecnico.nome}</option>)}</select></label><label>Prioridade<select aria-label="Filtrar prioridade" value={filters.prioridade || ''} onChange={e => update({ prioridade: e.target.value })}><option value="">Todas</option>{priorities.map(p => <option key={p} value={p}>{label(p)}</option>)}</select></label><label>Canal<select aria-label="Filtrar canal" value={filters.canal || ''} onChange={e => update({ canal: e.target.value })}><option value="">Todos</option>{channels.map(c => <option key={c} value={c}>{label(c)}</option>)}</select></label><Button variant="ghost" onClick={reset} title="Limpar filtros"><RotateCcw size={16}/><span className="sr-only">Limpar filtros</span></Button></div>{error && <p role="alert" className="text-rose-600 text-sm mt-2">{error}</p>}{directory.error && <ErrorBox error={directory.error} retry={() => void directory.refetch()}/>}</div>;
}
