import { useState, useEffect, Suspense } from 'react';
import { Loading } from './ui';
import { NavLink, Outlet, useLocation } from 'react-router-dom';
import { Headphones, LayoutDashboard, Ticket, ShieldCheck, Users, Building2, FileBarChart, Moon, Sun, Menu, X, ArrowUpRight } from 'lucide-react';
const links = [{ path: '/', label: 'Visão Geral', icon: LayoutDashboard }, { path: '/tickets', label: 'Tickets', icon: Ticket }, { path: '/sla', label: 'SLA', icon: ShieldCheck }, { path: '/equipe', label: 'Equipe', icon: Users }, { path: '/clientes', label: 'Clientes', icon: Building2 }, { path: '/relatorios', label: 'Relatórios', icon: FileBarChart }];
export function Layout() {
  const location = useLocation(); const [open, setOpen] = useState(false); const [dark, setDark] = useState(() => { const saved = localStorage.getItem('central-theme'); return saved ? saved === 'dark' : matchMedia('(prefers-color-scheme: dark)').matches; });
  useEffect(() => { document.documentElement.classList.toggle('dark', dark); }, [dark]);
  const globalParams = new URLSearchParams();
  for (const key of ['de', 'ate', 'equipeId', 'tecnicoId', 'prioridade', 'canal']) { const value = new URLSearchParams(location.search).get(key); if (value) globalParams.set(key, value); }
  const globalSearch = globalParams.size ? `?${globalParams}` : '';
  const active = links.find(l => l.path === location.pathname)?.label || 'Central';
  function toggleTheme() { setDark(value => { localStorage.setItem('central-theme', !value ? 'dark' : 'light'); return !value; }); }
  return <div className="app-shell">{open && <button className="sidebar-backdrop" aria-label="Fechar menu" onClick={() => setOpen(false)}/>}<aside className={`sidebar ${open ? 'sidebar-open' : ''}`}><div className="brand"><span><Headphones size={22}/></span><div><b>central<span>.</span></b><small>GESTÃO DE ATENDIMENTO</small></div><button className="icon-button mobile-close" aria-label="Fechar menu" onClick={() => setOpen(false)}><X size={20}/></button></div><div className="sidebar-label">ESPAÇO DE TRABALHO</div><nav aria-label="Navegação principal">{links.map(l => <NavLink key={l.path} to={`${l.path}${globalSearch}`} end={l.path === '/'} onClick={() => setOpen(false)} className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`}><l.icon size={19}/>{l.label}</NavLink>)}</nav><div className="sidebar-tip"><ShieldCheck size={22}/><strong>Cada atendimento importa</strong><p>Acompanhe prazos e mantenha sua equipe próxima de quem precisa.</p><NavLink to={`/sla${globalSearch}`} onClick={() => setOpen(false)}>Ver indicadores de SLA <ArrowUpRight size={14}/></NavLink></div><div className="sidebar-bottom"><div className="avatar">CS</div><div><strong>Central de suporte</strong><small>Operação de atendimento</small></div></div></aside><div className="workspace"><header className="topbar"><div><button className="icon-button mobile-menu" aria-label="Abrir menu" onClick={() => setOpen(true)}><Menu size={21}/></button><span className="muted">Workspace</span><span className="separator">/</span><b>{active}</b></div><div><span className="topbar-tag">Suporte ao cliente</span><button className="icon-button" aria-label={dark ? 'Ativar tema claro' : 'Ativar tema escuro'} onClick={toggleTheme}>{dark ? <Sun size={19}/> : <Moon size={19}/>}</button><span className="avatar avatar-small">CS</span></div></header><main><Suspense fallback={<Loading/>}><Outlet/></Suspense></main><footer className="app-footer">Central de Atendimento<span>Dados sincronizados com sua operação</span></footer></div></div>;
}
