import { useState, type FormEvent } from 'react';
import { useClientes, useDirectory, useTicketMutations } from '../hooks/queries';
import { channels, label, priorities, statuses, ticketInput, closed } from '../services/format';
import type { TicketDto, TicketInput, TicketDetalheDto } from '../types/api';
import { Button, ErrorBox, Loading } from './ui';
export function TicketForm({ ticket, onSaved, onCancel }: { ticket?: TicketDto; onSaved: (value: TicketDetalheDto) => void; onCancel: () => void }) {
  const clientes = useClientes(), directory = useDirectory(), mutations = useTicketMutations();
  const [input, setInput] = useState<TicketInput>(() => ticket ? ticketInput(ticket) : { assunto: '', descricao: '', clienteId: 0, tecnicoId: null, equipeId: null, prioridade: 'Media', canal: 'WhatsApp', status: 'Aberto', csat: null });
  const [validation, setValidation] = useState<string | null>(null);
  const mutation = ticket ? mutations.atualizar : mutations.criar; const busy = mutation.isPending;
  function change<K extends keyof TicketInput>(key: K, value: TicketInput[K]) { setInput(current => ({ ...current, [key]: value })); }
  async function submit(e: FormEvent) { e.preventDefault(); if (!input.assunto.trim() || !input.descricao.trim() || !input.clienteId) { setValidation('Informe assunto, descrição e cliente.'); return; } setValidation(null); try { const data = ticket ? await mutations.atualizar.mutateAsync({ id: ticket.id, input }) : await mutations.criar.mutateAsync(input); onSaved(data); } catch { /* A mutation apresenta o ProblemDetails abaixo. */ } }
  const teams = [...new Map((directory.data || []).map(t => [t.equipe.id, t.equipe])).values()];
  if (clientes.isPending || directory.isPending) return <Loading/>;
  if (clientes.error) return <ErrorBox error={clientes.error} retry={() => void clientes.refetch()}/>;
  if (directory.error) return <ErrorBox error={directory.error} retry={() => void directory.refetch()}/>;
  return <form className="form" onSubmit={e => void submit(e)}>{validation && <ErrorBox error={new Error(validation)}/>} {mutation.error && <ErrorBox error={mutation.error}/>}<fieldset disabled={busy}><label>Assunto<input required maxLength={200} value={input.assunto} onChange={e => change('assunto', e.target.value)} placeholder="Ex.: Erro na emissão de NF-e"/></label><label>Descrição<textarea required maxLength={10000} rows={4} value={input.descricao} onChange={e => change('descricao', e.target.value)} placeholder="Descreva o problema e os detalhes importantes…"/></label><label>Cliente<select required value={input.clienteId || ''} onChange={e => change('clienteId', Number(e.target.value))}><option value="">Selecione um cliente</option>{clientes.data?.map(c => <option key={c.id} value={c.id}>{c.nome}</option>)}</select></label><div className="form-row"><label>Equipe<select value={input.equipeId || ''} onChange={e => { change('equipeId', Number(e.target.value) || null); change('tecnicoId', null); }}><option value="">Sem equipe</option>{teams.map(t => <option key={t.id} value={t.id}>{t.nome}</option>)}</select></label><label>Técnico responsável<select value={input.tecnicoId || ''} onChange={e => { const id = Number(e.target.value) || null; change('tecnicoId', id); if (id) change('equipeId', directory.data?.find(t => t.tecnico.id === id)?.equipe.id || null); }}><option value="">Não atribuído</option>{directory.data?.filter(t => !input.equipeId || t.equipe.id === input.equipeId).map(t => <option key={t.tecnico.id} value={t.tecnico.id}>{t.tecnico.nome}</option>)}</select></label></div><div className="form-row"><label>Prioridade<select disabled={ticket && closed(ticket)} value={input.prioridade} onChange={e => change('prioridade', e.target.value as TicketInput['prioridade'])}>{priorities.map(p => <option value={p} key={p}>{label(p)}</option>)}</select></label><label>Canal<select value={input.canal} onChange={e => change('canal', e.target.value as TicketInput['canal'])}>{channels.map(c => <option value={c} key={c}>{label(c)}</option>)}</select></label></div>{ticket && <div className="form-row"><label>Status<select value={input.status} onChange={e => { const status = e.target.value as TicketInput['status']; change('status', status); if (!['Resolvido', 'Fechado'].includes(status)) change('csat', null); }}>{statuses.map(s => <option value={s} key={s}>{label(s)}</option>)}</select></label>{['Resolvido', 'Fechado'].includes(input.status) && <label>CSAT<select value={input.csat || ''} onChange={e => change('csat', Number(e.target.value) || null)}><option value="">Sem avaliação</option>{[1, 2, 3, 4, 5].map(n => <option key={n} value={n}>{n} / 5</option>)}</select></label>}</div>}</fieldset><div className="form-actions"><Button type="button" variant="secondary" onClick={onCancel} disabled={busy}>Cancelar</Button><Button busy={busy} type="submit">{ticket ? 'Salvar alterações' : 'Criar ticket'}</Button></div></form>;
}
