import { AlertCircle, ArrowDown, ArrowUp, Inbox, Loader2, RotateCw } from 'lucide-react';
import type { ReactNode, ButtonHTMLAttributes } from 'react';
import { ApiError } from '../services/api';
import { label, number } from '../services/format';
import type { KpiDto } from '../types/api';
export function Button({ children, variant = 'primary', busy, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'danger' | 'ghost'; busy?: boolean }) { return <button {...props} disabled={props.disabled || busy} className={`btn btn-${variant} ${props.className || ''}`}>{busy && <Loader2 size={16} className="animate-spin" />}{children}</button>; }
export function PageTitle({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="page-title"><div><h1>{title}</h1><p>{description}</p></div>{action}</div>; }
export function Panel({ title, description, action, children, className = '' }: { title?: string; description?: string; action?: ReactNode; children: ReactNode; className?: string }) { return <section className={`panel ${className}`}>{title && <div className="panel-head"><div><h2>{title}</h2>{description && <p>{description}</p>}</div>{action}</div>}{children}</section>; }
export function ErrorBox({ error, retry }: { error: unknown; retry?: () => void }) { const message = error instanceof Error ? error.message : 'Ocorreu um erro ao carregar os dados.'; const errors = error instanceof ApiError ? error.problem.errors : undefined; return <div role="alert" className="error-box"><AlertCircle size={20}/><div><strong>Não foi possível concluir</strong><p>{message}</p>{errors && <ul>{Object.entries(errors).map(([key, values]) => <li key={key}>{values.join(' ')}</li>)}</ul>}{retry && <Button variant="secondary" onClick={retry}><RotateCw size={14}/> Tentar novamente</Button>}</div></div>; }
export function Empty({ title = 'Nenhum resultado encontrado', message = 'Ajuste os filtros para consultar outros registros.', action }: { title?: string; message?: string; action?: ReactNode }) { return <div className="empty"><Inbox size={28}/><h3>{title}</h3><p>{message}</p>{action}</div>; }
export function Loading({ small = false }: { small?: boolean }) { return <div role="status" aria-label="Carregando dados" className={small ? 'py-5' : 'loading-grid'}>{Array.from({ length: small ? 2 : 4 }, (_, i) => <div className="skeleton" key={i}/>)}</div>; }
export function QueryState({ query, empty = false, children }: { query: { isPending: boolean; error: unknown; refetch: () => unknown }; empty?: boolean; children: ReactNode }) { if (query.isPending) return <Loading/>; if (query.error) return <ErrorBox error={query.error} retry={() => void query.refetch()}/>; if (empty) return <Empty/>; return <>{children}</>; }
export function Badge({ value }: { value: string }) { return <span className={`badge badge-${value}`}>{label(value)}</span>; }
export function KpiCard({ title, kpi, format = (v: number | null) => number(v), lowerBetter = false, icon }: { title: string; kpi: KpiDto; format?: (value: number | null) => string; lowerBetter?: boolean; icon?: ReactNode }) { const variation = kpi.variacaoPercentual; const positive = variation != null && (lowerBetter ? variation <= 0 : variation >= 0); return <div className="kpi-card"><div className="kpi-label">{title}<span>{icon}</span></div><strong>{format(kpi.valor)}</strong><div className={`kpi-variation ${variation == null ? 'muted' : positive ? 'text-emerald-600 dark:text-emerald-400' : 'text-rose-600 dark:text-rose-400'}`}>{variation == null ? <span>Sem base de comparação</span> : <>{variation >= 0 ? <ArrowUp size={14}/> : <ArrowDown size={14}/>}<b>{number(Math.abs(variation), 1)}%</b><span>vs. período anterior</span></>}</div></div>; }
export function Pagination({ page, total, size, onPage, onSize, busy }: { page: number; total: number; size: number; onPage: (page: number) => void; onSize?: (size: number) => void; busy?: boolean }) { const pages = Math.max(1, Math.ceil(total / size)); return <div className="pagination"><span>{total === 0 ? '0 registros' : `${(page - 1) * size + 1}–${Math.min(page * size, total)} de ${number(total)} registros`}</span><div>{onSize && <label>Por página <select aria-label="Registros por página" value={size} onChange={e => onSize(Number(e.target.value))}>{[20, 50, 100].map(n => <option key={n}>{n}</option>)}</select></label>}<Button variant="secondary" disabled={busy || page <= 1} onClick={() => onPage(page - 1)}>Anterior</Button><span>{page} / {pages}</span><Button variant="secondary" disabled={busy || page >= pages} onClick={() => onPage(page + 1)}>Próxima</Button></div></div>; }
