import { test, expect } from '@playwright/test';
const apiUrl = process.env.VITE_API_BASE_URL || 'http://localhost:5000';
test('Swagger e telas consultam os contratos reais', async ({ page, request }) => {
  const swagger = await (await request.get(`${apiUrl}/swagger/v1/swagger.json`)).json();
  const schemas = swagger.components.schemas;
  for (const name of ['TicketDto', 'ResumoDto', 'TicketDetalheDto', 'ConfiguracaoSlaDto', 'IndicadoresSlaDto', 'RankingDto', 'ClienteDto']) expect(schemas[name]).toBeTruthy();
  expect(Object.keys(schemas.TicketDto.properties)).toContain('sla');
  console.log('SWAGGER_CONTRACT ' + JSON.stringify({ paths: swagger.paths, schemas: Object.fromEntries(['TicketDto', 'ResumoDto', 'TicketDetalheDto', 'ConfiguracaoSlaDto', 'IndicadoresSlaDto', 'RankingDto', 'ClienteDto', 'MedicaoSla', 'HorarioComercial'].map(n => [n, schemas[n]])) }));
  await page.goto('/');
  await expect(page.getByText('Satisfação · CSAT')).toBeVisible();
  await expect(page.getByText('Primeira resposta', { exact: true })).toBeVisible();
  await expect(page.getByText('Não foi possível concluir')).toHaveCount(0);
  await expect(page.getByRole('status', { name: 'Carregando dados' })).toHaveCount(0);
  await page.waitForTimeout(1600);
  await page.screenshot({ path: 'test-results/dashboard-desktop.png', fullPage: true });
  for (const [path, title] of [['/sla', 'SLA'], ['/equipe', 'Equipe'], ['/clientes', 'Clientes'], ['/relatorios', 'Relatórios']]) {
    await page.goto(path); await expect(page.getByRole('heading', { name: title, exact: true })).toBeVisible();
    await expect(page.getByRole('status', { name: 'Carregando dados' })).toHaveCount(0);
    await expect(page.getByText('Não foi possível concluir')).toHaveCount(0);
  }
});
test('Novo ticket, nota interna, resposta, pausa, transferência e encerramento', async ({ page, request }) => {
  await page.goto('/tickets'); await page.getByRole('button', { name: 'Novo ticket' }).click();
  const modal = page.getByRole('dialog', { name: 'Novo ticket' });
  await modal.getByLabel('Assunto', { exact: true }).fill('E2E — Certificado digital de teste');
  await modal.getByLabel('Descrição', { exact: true }).fill('Falha ao transmitir NF-e. Verificar certificado.');
  await modal.getByLabel('Cliente', { exact: true }).selectOption('1');
  await modal.getByLabel('Técnico responsável').selectOption('1');
  await modal.getByRole('button', { name: 'Criar ticket', exact: true }).click();
  const drawer = page.getByRole('dialog'); await expect(drawer.getByRole('heading', { name: 'E2E — Certificado digital de teste' })).toBeVisible();
  const title = await drawer.getByRole('heading', { name: /Ticket #/ }).innerText(); const id = Number(title.split('#')[1]);
  await drawer.getByRole('button', { name: 'Nota interna', exact: true }).click();
  await drawer.getByLabel('Nota interna', { exact: true }).fill('Análise interna do certificado.');
  await drawer.getByRole('button', { name: 'Adicionar nota' }).click();
  await expect(drawer.getByText('Nota interna adicionada.')).toBeVisible();
  let detail = await (await request.get(`${apiUrl}/api/tickets/${id}`)).json(); expect(detail.ticket.primeiraRespostaEm).toBeNull();
  await drawer.getByRole('button', { name: 'Responder', exact: true }).click();
  await drawer.getByLabel('Mensagem', { exact: true }).fill('Olá! Vamos verificar seu certificado.');
  await drawer.getByRole('button', { name: 'Enviar resposta' }).click();
  await expect(drawer.getByText('Resposta enviada.')).toBeVisible();
  await drawer.getByLabel('Alterar status do ticket').selectOption('AguardandoCliente');
  await expect(drawer.getByText('Contagem pausada').first()).toBeVisible();
  await drawer.getByLabel('Transferir técnico').selectOption('2'); await drawer.getByRole('button', { name: 'Transferir', exact: true }).click();
  await expect(drawer.getByText('Responsável atualizado.')).toBeVisible();
  await drawer.getByLabel('Alterar status do ticket').selectOption('Resolvido');
  await expect(drawer.getByText('Reabra o ticket para enviar uma resposta pública.')).toBeVisible();
  detail = await (await request.get(`${apiUrl}/api/tickets/${id}`)).json(); expect(detail.ticket.status).toBe('Resolvido'); expect(detail.ticket.tecnico.id).toBe(2); expect(detail.ticket.primeiraRespostaEm).not.toBeNull();
  await drawer.getByRole('button', { name: 'Fechar', exact: true }).click();
});
test('Filtros, paginação, lote e Kanban persistem no servidor', async ({ page, request }) => {
  await page.goto('/tickets');
  await expect(page.getByText(/de .* registros/).first()).toBeVisible();
  const response = page.waitForResponse(r => r.url().includes('/api/tickets?') && r.url().includes('pagina=2') && r.request().method() === 'GET');
  await page.getByRole('button', { name: 'Próxima', exact: true }).click(); await response;
  await page.getByLabel('Filtrar status', { exact: true }).selectOption('Aberto');
  await page.getByLabel('Filtrar prioridade', { exact: true }).selectOption('Alta');
  const filtered = await (await request.get(`${apiUrl}/api/tickets?status=Aberto&prioridade=Alta&tamanhoPagina=100`)).json(); expect(filtered.itens.length).toBeGreaterThan(0);
  await page.getByRole('button', { name: 'Limpar filtros' }).click();
  await expect(page.locator('div[aria-busy]').first()).toHaveAttribute('aria-busy', 'false');
  const checkbox = page.getByRole('checkbox', { name: /Selecionar ticket / }).first(); await expect(checkbox).toBeVisible(); const id = Number((await checkbox.getAttribute('aria-label'))?.split(' ').at(-1));
  await checkbox.check(); await page.getByLabel('Status em lote').selectOption('EmAndamento');
  await page.getByRole('button', { name: 'Aplicar alterações' }).click(); await expect(page.getByText('1 ticket(s) atualizado(s).')).toBeVisible();
  expect((await (await request.get(`${apiUrl}/api/tickets/${id}`)).json()).ticket.status).toBe('EmAndamento');
  await page.getByRole('button', { name: 'Kanban', exact: true }).click();
  const card = page.getByTestId(`card-${id}`); await expect(card).toBeVisible();
  const dt = await page.evaluateHandle(() => new DataTransfer());
  await card.dispatchEvent('dragstart', { dataTransfer: dt });
  await page.getByTestId('column-AguardandoCliente').dispatchEvent('drop', { dataTransfer: dt });
  await expect(page.getByText(`Ticket #${id} movido para Aguardando cliente.`)).toBeVisible();
  expect((await (await request.get(`${apiUrl}/api/tickets/${id}`)).json()).ticket.status).toBe('AguardandoCliente');
  await page.screenshot({ path: 'test-results/tickets-kanban.png', fullPage: true });
});
test('Regras, clientes, exportação de todas as páginas e tema responsivo', async ({ page, request }) => {
  await page.goto('/sla'); const rules = await (await request.get(`${apiUrl}/api/sla/regras`)).json();
  await page.getByLabel('Primeira resposta Alta').fill(String(rules.regras.find((r: { prioridade: string }) => r.prioridade === 'Alta').primeiraRespostaMinutos));
  await page.getByRole('button', { name: 'Salvar regras' }).click(); await expect(page.getByText('Regras e expediente atualizados.')).toBeVisible();
  await page.goto('/clientes'); await page.getByRole('button', { name: 'Histórico' }).first().click(); await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('dialog').locator('tbody tr').first()).toBeVisible(); await page.getByRole('button', { name: 'Fechar', exact: true }).click();
  const start = new Date(); start.setDate(start.getDate() - 70); const end = new Date(); end.setDate(end.getDate() + 1);
  const day = (d: Date) => d.toISOString().slice(0, 10);
  await page.goto(`/relatorios?de=${day(start)}&ate=${day(end)}`);
  const until = new Date(`${day(end)}T00:00:00Z`); until.setUTCDate(until.getUTCDate() + 1);
  const total = (await (await request.get(`${apiUrl}/api/tickets?inicio=${day(start)}T00:00:00Z&fim=${until.toISOString()}&tamanhoPagina=1`)).json()).total;
  const download = page.waitForEvent('download'); await page.getByRole('button', { name: 'Exportar CSV' }).first().click(); const file = await download; expect(file.suggestedFilename()).toContain('central-tickets');
  await expect(page.getByText(`${total} registros exportados com sucesso.`)).toBeVisible();
  await page.getByRole('button', { name: 'Ativar tema escuro' }).click(); await expect(page.locator('html')).toHaveClass(/dark/); await page.reload(); await expect(page.locator('html')).toHaveClass(/dark/);
  await page.goto('/equipe'); await expect(page.getByText('Carga de trabalho')).toBeVisible(); await page.screenshot({ path: 'test-results/equipe-dark.jpg', type: 'jpeg', quality: 70, fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto('/');
  await page.getByRole('button', { name: 'Abrir menu' }).click(); await expect(page.getByRole('navigation')).toBeVisible();
  await page.getByRole('link', { name: 'Clientes', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Clientes', exact: true })).toBeVisible();
  const width = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, client: document.documentElement.clientWidth })); expect(width.scroll).toBeLessThanOrEqual(width.client);
  await page.screenshot({ path: 'test-results/clientes-mobile.jpg', type: 'jpeg', quality: 70, fullPage: true });
});
test('Estados de erro, recuperação e vazio', async ({ page }) => {
  await page.route('**/api/dashboard/resumo*', route => route.fulfill({ status: 500, contentType: 'application/problem+json', body: JSON.stringify({ title: 'Erro interno', detail: 'Falha temporária na operação.' }) }));
  await page.goto('/'); await expect(page.getByText('Falha temporária na operação.')).toBeVisible();
  await page.unroute('**/api/dashboard/resumo*'); await page.getByRole('button', { name: 'Tentar novamente' }).click(); await expect(page.getByText('Satisfação · CSAT')).toBeVisible();
  await page.goto('/tickets'); await page.getByRole('textbox', { name: 'Buscar tickets' }).fill('ZZZ_TICKET_INEXISTENTE_928384'); await page.getByRole('button', { name: 'Buscar', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Nenhum resultado encontrado' })).toBeVisible();
});
