import { useQuery } from '@tanstack/react-query';
import { Users, AlertTriangle, Trophy } from 'lucide-react';
import { useFilters } from '../hooks/useFilters';
import { api } from '../services/api';
import { duration, number } from '../services/format';
import { GlobalFilters } from '../components/GlobalFilters';
import { PageTitle, Panel, QueryState } from '../components/ui';
export function Equipe() {
  const { filters, error } = useFilters();
  const ranking = useQuery({ queryKey: ['ranking', filters], queryFn: ({ signal }) => api.ranking(filters, signal) });
  const carga = useQuery({ queryKey: ['carga', filters], queryFn: ({ signal }) => api.carga(filters, signal), refetchInterval: 30000 });
  return <><PageTitle title="Equipe" description="Equilibre a carga e reconheça os bons atendimentos."/><GlobalFilters/>{!error && <><Panel title="Ranking de técnicos" description="Ordenado pela quantidade de tickets resolvidos" action={<Trophy className="text-amber-500" size={22}/>}><QueryState query={ranking} empty={!ranking.data?.length}><div className="table-wrap"><table><thead><tr><th>Posição / Técnico</th><th>Equipe</th><th>Resolvidos</th><th>Tempo médio</th><th>SLA cumprido</th><th>CSAT</th></tr></thead><tbody>{ranking.data?.map((r, i) => <tr key={r.tecnico.id}><td><div className="ranking-person"><span className={`rank rank-${i + 1}`}>{i + 1}</span><b>{r.tecnico.nome}</b></div></td><td>{r.equipe.nome}</td><td><b>{r.resolvidos}</b></td><td>{duration(r.tempoMedioResolucaoMinutos)}</td><td>{r.slaCumpridoPercentual == null ? '—' : `${number(r.slaCumpridoPercentual, 1)}%`}</td><td>{r.csat == null ? '—' : `${number(r.csat, 1)} / 5`}</td></tr>)}</tbody></table></div></QueryState></Panel><Panel title="Carga de trabalho" description="Tickets ativos criados no período selecionado" action={<Users size={22} className="text-brand-500"/>}><QueryState query={carga} empty={!carga.data?.length}><div className="load-grid">{carga.data?.map(c => <article className={`load-card ${c.sobrecarga ? 'overloaded' : ''}`} key={c.tecnico.id}><header><span className="avatar">{c.tecnico.nome.split(' ').slice(0, 2).map(n => n[0]).join('')}</span><div><b>{c.tecnico.nome}</b><small>{c.equipe.nome}</small></div></header><div className="load-total"><b>{c.total}</b><span>tickets ativos</span>{c.sobrecarga && <span className="overload-label"><AlertTriangle size={13}/> Sobrecarga</span>}</div><div className="load-bars"><span style={{ width: `${c.total ? c.abertos / c.total * 100 : 0}%` }} title="Abertos"/><span style={{ width: `${c.total ? c.emAndamento / c.total * 100 : 0}%` }} title="Em andamento"/><span style={{ width: `${c.total ? c.aguardandoCliente / c.total * 100 : 0}%` }} title="Aguardando cliente"/></div><div className="load-counts"><span><i/>{c.abertos} abertos</span><span><i/>{c.emAndamento} em andamento</span><span><i/>{c.aguardandoCliente} aguardando</span></div></article>)}</div></QueryState></Panel></>}</>;
}
