import { useEffect, useRef, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Download, FileSpreadsheet, ShieldCheck, Users, X } from 'lucide-react';
import { api, exportTickets } from '../services/api';
import { csv, dateTime, downloadCsv, label } from '../services/format';
import { useFilters } from '../hooks/useFilters';
import { GlobalFilters } from '../components/GlobalFilters';
import { Button, ErrorBox, PageTitle, Panel, QueryState } from '../components/ui';
export function Relatorios() {
  const { filters, period, error } = useFilters(); const [busy, setBusy] = useState(false), [progress, setProgress] = useState(''), [failure, setFailure] = useState<unknown>(null), [success, setSuccess] = useState(''); const abort = useRef<AbortController | null>(null);
  const resumo = useQuery({ queryKey: ['resumo', filters], queryFn: ({ signal }) => api.resumo(filters, signal) });
  useEffect(() => () => abort.current?.abort(), []);
  async function exportReport(type: 'tickets' | 'sla' | 'equipe') {
    if (busy || error) return; const controller = new AbortController(); abort.current = controller; setBusy(true); setFailure(null); setSuccess(''); setProgress('Preparando dados…');
    try {
      let rows: (string | number | null)[][];
      if (type === 'tickets') { const tickets = await exportTickets(filters, controller.signal, (count, total) => setProgress(`${count} de ${total} tickets carregados`)); rows = [['ID', 'Assunto', 'Descrição', 'Cliente', 'Técnico', 'Equipe', 'Prioridade', 'Status', 'Canal', 'Abertura', 'Atualização', 'Primeira resposta', 'Resolução', 'SLA resposta (min restantes)', 'SLA resolução (min restantes)', 'CSAT'], ...tickets.map(t => [t.id, t.assunto, t.descricao, t.cliente.nome, t.tecnico?.nome || '', t.equipe?.nome || '', label(t.prioridade), label(t.status), label(t.canal), dateTime(t.criadoEm), dateTime(t.atualizadoEm), dateTime(t.primeiraRespostaEm), dateTime(t.resolvidoEm), t.sla.primeiraResposta.restanteMinutos, t.sla.resolucao.restanteMinutos, t.csat])]; }
      else if (type === 'sla') { const results = await api.violacoes(filters, controller.signal); rows = [['ID', 'Assunto', 'Cliente', 'Técnico', 'Prioridade', 'Motivos', 'Resposta consumida (min)', 'Resolução consumida (min)'], ...results.map(v => [v.ticket.id, v.ticket.assunto, v.ticket.cliente.nome, v.ticket.tecnico?.nome || '', label(v.ticket.prioridade), v.motivos.join(' | '), v.ticket.sla.primeiraResposta.consumidoMinutos, v.ticket.sla.resolucao.consumidoMinutos])]; }
      else { const results = await api.ranking(filters, controller.signal); rows = [['Técnico', 'Equipe', 'Resolvidos', 'Tempo médio resolução (min)', 'SLA cumprido (%)', 'CSAT'], ...results.map(r => [r.tecnico.nome, r.equipe.nome, r.resolvidos, r.tempoMedioResolucaoMinutos, r.slaCumpridoPercentual, r.csat])]; }
      if (controller.signal.aborted) return;
      if (rows.length <= 1) { setSuccess('Não há registros para exportar neste período.'); return; }
      downloadCsv(csv(rows), `central-${type}-${period.de || 'inicio'}-${period.ate || 'hoje'}.csv`); setSuccess(`${rows.length - 1} registros exportados com sucesso.`);
    } catch (e) { if (!controller.signal.aborted) setFailure(e); } finally { setBusy(false); setProgress(''); abort.current = null; }
  }
  return <><PageTitle title="Relatórios" description="Transforme os atendimentos em informação para sua equipe."/><GlobalFilters/>{!error && <><Panel title="Exportações" description="Os arquivos respeitam o período e os filtros selecionados."><div className="report-grid">{([{ type: 'tickets', title: 'Histórico de tickets', description: 'Todos os tickets do período, incluindo dados do cliente, responsáveis, prazos e avaliações.', icon: FileSpreadsheet }, { type: 'sla', title: 'Violações de SLA', description: 'Tickets fora do prazo, motivos de violação e tempo consumido em cada etapa.', icon: ShieldCheck }, { type: 'equipe', title: 'Desempenho da equipe', description: 'Resoluções, tempo médio, cumprimento de SLA e satisfação por técnico.', icon: Users }] as const).map(r => <article key={r.type} className="report-card"><span><r.icon size={24}/></span><h3>{r.title}</h3><p>{r.description}</p><Button variant="secondary" disabled={busy} onClick={() => void exportReport(r.type)}><Download size={16}/> Exportar CSV</Button></article>)}</div>{busy && <div role="status" className="export-progress"><span>{progress}</span><Button variant="ghost" onClick={() => abort.current?.abort()}><X size={14}/> Cancelar exportação</Button></div>}{failure != null && <div className="p-5"><ErrorBox error={failure}/></div>}{success && <p role="status" className="success-note m-5">{success}</p>}<p className="report-footnote">CSV em UTF-8, com separador ponto e vírgula, compatível com Excel. A exportação de tickets percorre todas as páginas da API.</p></Panel><Panel title="Resumo do período" description="Referência para acompanhar a exportação"><QueryState query={resumo}>{resumo.data && <div className="summary-facts"><div><span>Abertos</span><b>{resumo.data.abertos.valor ?? '—'}</b></div><div><span>Em andamento</span><b>{resumo.data.emAndamento.valor ?? '—'}</b></div><div><span>Resolvidos no último dia</span><b>{resumo.data.resolvidosHoje.valor ?? '—'}</b></div><div><span>SLA cumprido</span><b>{resumo.data.slaCumpridoPercentual.valor == null ? '—' : `${resumo.data.slaCumpridoPercentual.valor.toFixed(1).replace('.', ',')}%`}</b></div></div>}</QueryState></Panel></>}</>;
}
