import { useState, type FormEvent } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Save, ShieldCheck, AlertTriangle, Clock3 } from 'lucide-react';
import { BarChart, Bar, CartesianGrid, XAxis, YAxis, Tooltip, ResponsiveContainer, Legend } from 'recharts';
import { api } from '../services/api';
import { useRegras, useSaveRules } from '../hooks/queries';
import { useFilters } from '../hooks/useFilters';
import type { ConfiguracaoSlaDto, DiaSemana } from '../types/api';
import { GlobalFilters } from '../components/GlobalFilters';
import { Badge, Button, ErrorBox, PageTitle, Panel, QueryState } from '../components/ui';
import { TicketDrawer } from '../components/TicketDrawer';
import { number, shortDate } from '../services/format';
const days: [DiaSemana, string][] = [['Monday', 'Seg'], ['Tuesday', 'Ter'], ['Wednesday', 'Qua'], ['Thursday', 'Qui'], ['Friday', 'Sex'], ['Saturday', 'Sáb'], ['Sunday', 'Dom']];
function RulesEditor({ original }: { original: ConfiguracaoSlaDto }) {
  const [value, setValue] = useState(() => structuredClone(original)), [saved, setSaved] = useState(false), [error, setError] = useState<string | null>(null); const mutation = useSaveRules();
  function editRule(index: number, key: 'primeiraRespostaMinutos' | 'resolucaoMinutos', minutes: number) { setSaved(false); setValue(current => ({ ...current, regras: current.regras.map((r, i) => i === index ? { ...r, [key]: minutes } : r) })); }
  async function submit(e: FormEvent) { e.preventDefault(); setError(null); if (!value.horario.dias.length || value.horario.fim <= value.horario.inicio || value.regras.some(r => r.resolucaoMinutos < r.primeiraRespostaMinutos)) { setError('Escolha ao menos um dia, fim após o início e prazo de resolução maior ou igual ao de primeira resposta.'); return; } try { new Intl.DateTimeFormat('pt-BR', { timeZone: value.horario.fusoHorario }); } catch { setError('Informe um fuso horário válido.'); return; } try { await mutation.mutateAsync(value); setSaved(true); } catch { /* ProblemDetails exibido abaixo. */ } }
  return <form className="rule-form" onSubmit={e => void submit(e)}><fieldset disabled={mutation.isPending}><div className="table-wrap"><table><thead><tr><th>Prioridade</th><th>1ª resposta (minutos)</th><th>Resolução (minutos)</th></tr></thead><tbody>{value.regras.map((r, i) => <tr key={r.prioridade}><td><Badge value={r.prioridade}/></td><td><input aria-label={`Primeira resposta ${r.prioridade}`} type="number" required min={1} max={525600} step={1} value={r.primeiraRespostaMinutos} onChange={e => editRule(i, 'primeiraRespostaMinutos', Number(e.target.value))}/></td><td><input aria-label={`Resolução ${r.prioridade}`} type="number" required min={r.primeiraRespostaMinutos} max={525600} step={1} value={r.resolucaoMinutos} onChange={e => editRule(i, 'resolucaoMinutos', Number(e.target.value))}/></td></tr>)}</tbody></table></div><div className="schedule"><h3>Horário comercial</h3><p>O relógio conta somente nestes dias e horários.</p><div className="weekdays">{days.map(([day, name]) => <label key={day} className={value.horario.dias.includes(day) ? 'checked' : ''}><input type="checkbox" checked={value.horario.dias.includes(day)} onChange={e => { setSaved(false); setValue(current => ({ ...current, horario: { ...current.horario, dias: e.target.checked ? [...current.horario.dias, day] : current.horario.dias.filter(d => d !== day) } })); }}/>{name}</label>)}</div><div className="form-row"><label>Início<input aria-label="Início do expediente" required type="time" value={value.horario.inicio.slice(0, 5)} onChange={e => { setSaved(false); setValue(v => ({ ...v, horario: { ...v.horario, inicio: `${e.target.value}:00` } })); }}/></label><label>Fim<input aria-label="Fim do expediente" required type="time" value={value.horario.fim.slice(0, 5)} onChange={e => { setSaved(false); setValue(v => ({ ...v, horario: { ...v.horario, fim: `${e.target.value}:00` } })); }}/></label><label>Fuso horário<input list="timezones" required value={value.horario.fusoHorario} onChange={e => { setSaved(false); setValue(v => ({ ...v, horario: { ...v.horario, fusoHorario: e.target.value } })); }}/><datalist id="timezones"><option>America/Fortaleza</option><option>America/Sao_Paulo</option><option>UTC</option></datalist></label></div></div></fieldset><div className="rule-footer"><p>Alterações globais valem para novos tickets. Tickets existentes preservam o horário registrado na abertura.</p><Button type="submit" busy={mutation.isPending}><Save size={16}/> Salvar regras</Button></div>{saved && <p role="status" className="success-note m-5">Regras e expediente atualizados.</p>}{error && <div className="p-5"><ErrorBox error={new Error(error)}/></div>}{mutation.error && <div className="p-5"><ErrorBox error={mutation.error}/></div>}</form>;
}
export function Sla() {
  const { filters, error } = useFilters(); const regras = useRegras(); const [drawer, setDrawer] = useState<number | null>(null);
  const indicadores = useQuery({ queryKey: ['indicadores', filters], queryFn: ({ signal }) => api.indicadores(filters, signal), refetchInterval: 30000 });
  const violacoes = useQuery({ queryKey: ['violacoes', filters], queryFn: ({ signal }) => api.violacoes(filters, signal), refetchInterval: 30000 });
  const data = indicadores.data;
  return <><PageTitle title="SLA" description="Prazos claros para uma operação mais previsível."/><GlobalFilters/>{!error && <><QueryState query={indicadores}><div className="metric-grid"><div className="metric-card metric-green"><ShieldCheck/><span>Cumpridos</span><b>{number(data?.cumpridos)}</b><small>{number(data?.percentualCumprido, 1)}% dos encerrados</small></div><div className="metric-card metric-red"><AlertTriangle/><span>Violados</span><b>{number(data?.violados)}</b><small>Inclui tickets ainda ativos</small></div><div className="metric-card metric-yellow"><Clock3/><span>Em risco</span><b>{number(data?.emRisco)}</b><small>Menos de 20% do prazo restante</small></div></div></QueryState><div className="sla-page-grid"><Panel title="Regras de atendimento" description="Prazos por prioridade e expediente"><QueryState query={regras}>{regras.data && <RulesEditor original={regras.data}/>}</QueryState></Panel><Panel className="sla-evolution-panel" title="Evolução semanal" description="Resoluções agrupadas por semana"><QueryState query={indicadores} empty={!data?.evolucaoSemanal.length}><div className="chart chart-tall"><ResponsiveContainer width="100%" height="100%"><BarChart data={data?.evolucaoSemanal.map(s => ({ ...s, semana: shortDate(s.semana) }))}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="semana" axisLine={false} tickLine={false}/><YAxis allowDecimals={false} axisLine={false} tickLine={false}/><Tooltip contentStyle={{ background: 'var(--surface)', borderColor: 'var(--border)', borderRadius: 10 }}/><Legend iconType="circle"/><Bar dataKey="cumpridos" name="Cumpridos" stackId="a" fill="#10b981"/><Bar dataKey="violados" name="Violados" stackId="a" fill="#ef4444" radius={[4, 4, 0, 0]}/></BarChart></ResponsiveContainer></div></QueryState><div className="sla-legend"><Badge value="NoPrazo"/><Badge value="EmRisco"/><Badge value="Violado"/></div></Panel></div><Panel title="Violações de SLA" description="Identifique atrasos e seus motivos"><QueryState query={violacoes} empty={!violacoes.data?.length}><div className="table-wrap"><table><thead><tr><th>Ticket</th><th>Cliente</th><th>Técnico</th><th>Prioridade</th><th>Motivo</th></tr></thead><tbody>{violacoes.data?.map(v => <tr key={v.ticket.id}><td><button className="table-link" onClick={() => setDrawer(v.ticket.id)}><small>#{v.ticket.id}</small>{v.ticket.assunto}</button></td><td>{v.ticket.cliente.nome}</td><td>{v.ticket.tecnico?.nome || 'Não atribuído'}</td><td><Badge value={v.ticket.prioridade}/></td><td className="violation-reason">{v.motivos.join(' · ')}</td></tr>)}</tbody></table></div></QueryState></Panel></>}{drawer && <TicketDrawer id={drawer} onClose={() => setDrawer(null)}/>}</>;
}
